### ISSUE TITLE
Images don't scan

### ISSUE THREAD

**Issue by daveloyall** [HughChen/qr_image#1]
Hi, I tested all four images as seen in `README.md`, `demo.png`, and `demo_chrono.png`.

None scanned, unfortunately.  I tried quite a bit.  You know, carefully positioning the camera, cleaning the lens, etc.

I'm using [SecScanQR](https://github.com/Fr4gorSoftware/SecScanQR/) 1.2.8 (Build 21) which uses the [ZXING](https://github.com/zxing/zxing) Library (version 3.4.0).

**Comment by fersarr** [comment]
My images also were not scanned properly after download. One of them worked when scanned off of the website (before download)
I used this image for getspatially.com
![sp_logo](https://user-images.githubusercontent.com/3913371/152023733-ba4342c5-64b4-4b3e-9788-527057268346.png)

**Comment by daveloyall** [comment]
@fersarr, oh, you used that as an input image, and then generated a QR image as a result, and the result did not scan?

That gave me an idea!  I tried using a blank, white image as the input.  I got this result...

![qr_image](https://user-images.githubusercontent.com/1524866/152026472-b49f69e4-2924-4bb3-b3ef-e4243f5b6f80.png)

But, I can't scan it using my phone.  (SecScanQR as described above.)

(when I tried scanning it, it was presented on a white background.  It may look different when you read this, if the background isn't white.)

**Comment by ShyWolf42** [comment]
Same issue, with the android app "Barcode scan" by zxing

posted image does not scan, the demo image only scans the 1st and 3rd image, but it's a hassle and takes a long time. (1st image being much more reliable)

normal QR codes scan in less than a second.

**Comment by HughChen** [comment]
Hello - I think there are two separate issues:

1. @fersarr The issue is probably that you need a white border around the QR codes.  That would explain why they scan on the website but not after you download them.  There is a button you can toggle to add a white background and a slider to change the border width.

2. @daveloyall and @agnag Your issue sounds tougher.  I only tested using an iPhone and an iPad, whose built-in QR code readers are able to read these.  Their QR code readers likely samples bits from the center regions of each square.  It sounds like this is not the case for the QR code reader you are using.  I am not aware of a simple way to fix this unfortunately (and I don't think there is any approach that will be guaranteed to work for any reader :/).  Sorry about that!  Also, I mentioned that this site may not work for all QR code readers in the youtube video, but I will also add it to the site itself for clarity.

**Comment by fersarr** [comment]
Thank you! yep adding a white background and border size of 3 made it readable by the default camera on Android and iPhone. Now the image below goes to https://getspatially.com/. Gave you a shout out! https://twitter.com/fersarr/status/1488861747335380995?s=20&t=R1e2Ds_qAkiqT9P_n-iBKw
![qr_image (1)](https://user-images.githubusercontent.com/3913371/152158946-32c19b14-2367-4885-84e5-c04ae17d22d6.png)

**Comment by AndreasFreund** [comment]
I think another problem could be, that the qr-codes come out flipped. I generated the same QR-Code using [this](https://www.nayuki.io/page/qr-code-generator-library) generator. As you can see in the screenshot, the Qr-Code is flipped along the diagonal. X and Y probably got swapped somewhere. After adding transform:scaleX(-1) to the image css, effectively unflipping it, my phone can scan the qr-code again.
![Screenshot](https://user-images.githubusercontent.com/1886417/152196781-952c3bd2-b055-4c03-a8b9-b9e02b8e79a0.png)

**Comment by HughChen** [comment]
@AndreasFreund 

Great catch - I will fix this after work!

**Comment by HughChen** [comment]
Alright - should be good now: ebad938479204e454c3c227f2dd646d1afadd406.
